development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test: &TEST
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: teambox2_test

production:
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: teambox2_production

cucumber:
  <<: *TEST